// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH3Wksymk7Yg8Yop6H9Lt5wYcjbQxL5KI',
    appId: '1:642018275450:web:e823b10e37baf8ed2dcbc3',
    messagingSenderId: '642018275450',
    projectId: 'dicoding-first-project-a68b5',
    authDomain: 'dicoding-first-project-a68b5.firebaseapp.com',
    storageBucket: 'dicoding-first-project-a68b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9lZ-vFmUvX38h00xW5xFMx91VamUPZ-U',
    appId: '1:642018275450:android:c73b44dc41bf80202dcbc3',
    messagingSenderId: '642018275450',
    projectId: 'dicoding-first-project-a68b5',
    storageBucket: 'dicoding-first-project-a68b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDKKfdawaaQSh6mWLOkjMgJcZHBmwse_8',
    appId: '1:642018275450:ios:5e8b44ac2ffe6d542dcbc3',
    messagingSenderId: '642018275450',
    projectId: 'dicoding-first-project-a68b5',
    storageBucket: 'dicoding-first-project-a68b5.appspot.com',
    iosBundleId: 'com.dicoding.dicodingChatting',
  );
}
